article/urls.py
from django.conf.urls import url
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^$', views.home),
    url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^test/$', views.test),
    url(r'^archives/$', views.archives, name='archives'),
    url(r'^aboutus/$', views.about_us, name='about_us'),
    url(r'^tag(?P<tag>\w+)/$', views.search_tag, name='search_tag'),
    url(r'^create_notice/$', views.create_notice, name='create_notice'),
    url(r'^comment/$', views.post_comment, name='post_comment'),
    url(r'^(?P<id>[0-9]+)/del/$', views.del_post, name='del_post'),
    url(r'^(?P<id>[0-9]+)/edit/$$', views.edit_post, name='edit_post')

]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from article import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^article/', include('article.urls')),
    url(r'^usermanage/', include('usermanage.urls')),
]

usermanage/urls.py
from django.conf.urls import url
from . import views

app_name = 'usermanage'

urlpatterns = [
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

]

article/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    category = models.CharField(max_length = 50, blank = True)
    date_time = models.DateTimeField(auto_now_add = True)
    author = models.CharField(max_length=50, default='NULL')
    content = models.TextField(blank = True, null = True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-date_time']

class Comment(models.Model):
    user_name = models.CharField(max_length=100)
    content = models.TextField('')
    date_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey('Article', on_delete=models.CASCADE)


    def __unicode__(self):
        return self.content[:20]

    class Meta:
        ordering = ['-date_time']

usermanage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {

            # <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">


            'content': forms.Textarea(attrs={'data-provide' : 'markdown', 'placeholder' : 'Write your comment here'}),
        }

usermanage/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'email', 'password']

article/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article, Comment
from datetime import datetime
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ArticleForm, CommentForm
from django.shortcuts import redirect, get_object_or_404

# Create your views here.

def home(request):
    posts = Article.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.paginator(paginator.num_pages)
    return render(request, 'home.html', {'post_list' : post_list})

def detail(request, id):
    try:
        post = Article.objects.get(id=str(id))
        comment_list = Comment.objects.filter(article=post)
    except Article.DoesNotExist:
        raise Http404
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = post
            comment.user_name = request.user
            comment.save()
            return redirect('/article/' + str(id))
    else:
        form = CommentForm()
    return render(request, 'post.html', {'post' : post, 'comment_list' : comment_list, 'form' : form})

def test(request):
    return render(request, 'test.html', {'current_time': datetime.now()})

def archives(request):
    try:
        post_list = Article.objects.all()
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'archives.html', {'post_list' : post_list, 'error' : False})

def about_us(request):
    return render(request, 'aboutus.html')

def search_tag(request, tag):
    try:
        post_list = Article.objects.filter(category__iexact = tag)
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'tag.html', {'post_list' : post_list})

def create_notice(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.author = request.user
            notice.save()
            return redirect('/article')
    else:
        form = ArticleForm()
    return render(request, 'new_notice.html', {'form' : form})

def post_comment(request, article_id):#unavaliable
    if request.method.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user_name = request.user
            comment.save()
            return redirect('/article')
    else:
        form = CommentForm()
        return render(request, 'post.html', {'form' : form})

def edit_post(request, id):
    post = get_object_or_404(Article, pk=id)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/article/' + id, pk=post.pk)
    else:
        form = ArticleForm(instance=post)
    return render(request, 'post_edit.html', {'form': form})

def del_post(request, id):
    post = get_object_or_404(Article, pk=id)
    post.delete()
    return redirect('/article')

usermanage/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.views.generic import View
from django.contrib.auth import authenticate, login

# Create your views here.

class UserFormView(View):
    form_class = UserForm
    template_name = 'register_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            #cleaned data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('article')
        return render(request, self.template_name, {'form' : form})

templates/aboutus.html
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
<div class="posts">
        <p> About us - The phoenix </p>
</div><!-- /.blog-post -->
{% endblock %}

templates/archives.html
{% extends "base.html" %}

{% block content %}

<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url 'detail' id=post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="{% url 'search_tag' tag=post.category %}">{{ post.category }}</a>
                    </p>
            </header>
        </section>
    {% endfor %}
</div><!-- /.blog-post -->
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a blog page with a list of posts.">
    <title>{% block title %} SHNU e-Bulltin by PHOENIX {% endblock %}</title>
    <link rel="stylesheet" href="http://labfile.oss.aliyuncs.com/courses/487/pure-min.css">
    <link rel="stylesheet" href="http://labfile.oss.aliyuncs.com/courses/487/grids-responsive-min.css">
    <link rel="stylesheet" href="http://labfile.oss.aliyuncs.com/courses/487/blog.css">
    <link rel="stylesheet" href="http://labfile.oss.aliyuncs.com/courses/487/monokai.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title">PHOENIX</h1>
            <h2 class="brand-tagline">SHNU e-Bulltin</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="#">Register</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">NOTICE</a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="{% url 'article:create_notice' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;New Notice
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul>
                        <li><a href="/article/aboutus/">About Us</a></li>
                        <li><a href="#">Weibo</a></li>
                        <li><a href="http://github.com/">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">Comments</p>
        <form method="post" action="{% url 'article:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">Post</button>
        </form>
        <p class="comment-count">{{ 0 }}Comments</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.date_time }}</time>
                <div class="comment-content">
                    {{ comment.content }}
                </div>
                  <a href="">Reply</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

templates/editor.html
{% extends 'base.html' %}
{% block content %}
    <h3>CREATE NEW NOTICE</h3>
    <form method="POST" class="notice-form">{% csrf_token %}
        {{  form.as_p }}
        <button type="submit" class="save btn btn-default">CREATE</button>
    </form>
{% endblock %}

templates/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/home.html
{% extends "base.html" %}

{% load custom_markdown %}
{% block content %}
<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url 'article:detail' id=post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:"Y M d"}}</a> <a class="post-category post-category-js" href="{% url 'article:search_tag' tag=post.category %}">{{ post.category|title }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|custom_markdown|truncatewords:10 }}
                    </p>
                </div>
                <a class="pure-button" href="{% url 'article:detail' id=post.id %}">Read More >>> </a>
        </section>
    {% endfor %}

    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
      <div>
      <ul class="pager">
      {% if post_list.has_previous %}
        <li><a href="?page={{ post_list.previous_page_number }}">Prev Page</a></li>
      {% endif %}

      {% if post_list.has_next %}
        <li><a href="?page={{ post_list.next_page_number }}">Next Page</a></li>
      {% endif %}
      </ul>
      </div>
    {% endif %}
</div><!-- /.blog-post -->
{% endblock %}

templates/new_notice.html
{% extends 'base.html' %}
{% block content %}
    <h3>CREATE A NEW NOTICE</h3>
    <form method="POST" class="notice-form">{% csrf_token %}
        {{  form.as_p }}
        <button type="submit" class="save btn btn-default">Create</button>
    </form>
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% load custom_markdown %} #new added code

{% block content %}
<div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}  <a class="btn btn-default" href="{% url 'article:edit_post' id=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-default" href="{% url 'article:del_post' id=post.pk  %}"><span class="glyphicon glyphicon-remove"></span></a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time|date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="{% url 'article:search_tag' tag=post.category %}">{{ post.category }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|custom_markdown }}
                    </p>
                </div>
        </section>
</div><!-- /.blog-post -->
<br>
<br>
<br>
<br>
<HR style="FILTER: alpha(opacity=100,finishopacity=0,style=3)" width="80%" color=#987cb9 SIZE=3>
<br>
<div class="comment">
    <h3>Leave your comments</h3>
    <div class="comment-main">
            <form method="POST" class="comment-form">{% csrf_token %}
                {{  form.as_p }}
                <button type="submit" class="btn btn-large btn-info">Post</button>
            </form>
        <h3 class="comment-count">{{ comment_list.count }} Comment(s)</h3>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.date_time }}</time>
                <div class="comment-content">
                    {{ comment.content }}
                </div>
                  <a href="">Reply</a>
            </div>
            <hr>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/post_edit.html
{% extends 'base.html' %}
{% block content %}
    <h3>Edit your notice</h3>
    <form method="POST" class="notice-form">{% csrf_token %}
        {{  form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/register_form.html
{% extends "base.html" %}

{% block body %}

    <a href="#">aaaa</a>


{% endblock %}

templates/tag.html
<!DOCTYPE html>
<html lang="en">
<head>{% extends "base.html" %}

{% load custom_markdown %}
{% block content %}
<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url 'article:detail' id=post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:"Y M d"}}</a> <a class="post-category post-category-js" href="{% url 'article:search_tag' tag=post.category %}">{{ post.category|title }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|custom_markdown }}
                    </p>
                </div>
                <a class="pure-button" href="{% url 'article:detail' id=post.id %}">Read More >>> </a>
        </section>
    {% endfor %}
</div><!-- /.blog-post -->
{% endblock %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Just test template</title>
    <style>
        body {
            background-color: red
        }
        em {
            color: LightSeaGreen
        }
    </style>
</head>
<body>
    <h1>Hello World</h1>
    <strong>{{ current_time }}</strong>
</body>
</html>